repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0  # Use the latest version
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

ci:
    autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate' 