coverage:
  status:
    project:
      default:
        target: 95%    # coverage target percentage
        threshold: 1%  # allow coverage to drop by 1% while still passing
    patch:
      default:
        target: 95%    # new code should have 95% coverage
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no       # [yes :: must have a base report to post]
  require_head: yes      # [yes :: must have a head report to post]

ignore:
  - "tests/"
  - "app/migrations/"
  - "app/__init__.py" 